### ISSUE TITLE
making a release?

### ISSUE THREAD

**Issue by xtraeme** [rmind/rvault#21]
Hi rmind, would you like to create a tagged release for inclusion in void?

**Comment by rmind** [comment]
Hi @xtraeme! Long time no see. :)

Yes, absolutely. I will soon create a tag and will publish the release on Github with the packages for Linux and MacOS.

While **rvault** is generally ready for use, I want to polish a few things and test some corner cases before making a formal release. So, let's bake it for a week or two. I'll ping you on this issue once the release will be available. Meanwhile, if you have any questions, just let me know.

**Comment by rmind** [comment]
@xtraeme: Just to let you know -- I created a tagged release.

**Comment by rmind** [comment]
@xtraeme Please use at least v0.2 tag. Thanks.
